# Generated by Django 2.1.7 on 2024-11-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20230821_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Seat',
            field=models.CharField(choices=[('KS-Plant5', 'KS-Plant5'), ('KS-Plant3', 'KS-Plant3'), ('KS-Plant2', 'KS-Plant2'), ('CQ', 'CQ'), ('CD', 'CD'), ('TPE', 'TPE'), ('PCP', 'PCP'), ('LKE', 'LKE')], default='KS-Plant5', max_length=108),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(1, '测试部门'), (3, 'PM'), (4, '其它部门'), (2, '开发部门')], default=1, verbose_name='部门'),
        ),
    ]
