# Generated by Django 2.1.7 on 2025-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabinetManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='柜体名称'),
        ),
    ]
