# Generated by Django 2.1.7 on 2025-08-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabinetManage', '0002_auto_20250804_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetgrid',
            name='Back_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='放回日期'),
        ),
        migrations.AlterField(
            model_name='cabinetgrid',
            name='Brow_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='留樣日期'),
        ),
        migrations.AlterField(
            model_name='cabinetgrid',
            name='Take_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拿取日期'),
        ),
    ]
