# Generated by Django 2.1.7 on 2025-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabinetManage', '0004_auto_20250804_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetgrid',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '空闲'), (1, '使用中'), (2, '预定中'), (3, '拿取保留中')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='gridrecord',
            name='new_status',
            field=models.CharField(choices=[(0, '空闲'), (1, '使用中'), (2, '预定中'), (3, '拿取保留中')], max_length=20, verbose_name='新状态'),
        ),
        migrations.AlterField(
            model_name='gridrecord',
            name='old_status',
            field=models.CharField(choices=[(0, '空闲'), (1, '使用中'), (2, '预定中'), (3, '拿取保留中')], max_length=20, verbose_name='原状态'),
        ),
    ]
