# Generated by Django 2.1.7 on 2025-08-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabinetManage', '0006_auto_20250805_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridrecord',
            name='new_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '空闲'), (1, '使用中'), (2, '预定中'), (3, '拿取保留中')], verbose_name='新状态'),
        ),
        migrations.AlterField(
            model_name='gridrecord',
            name='old_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '空闲'), (1, '使用中'), (2, '预定中'), (3, '拿取保留中')], verbose_name='原状态'),
        ),
    ]
