# Generated by Django 2.1.7 on 2025-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabinetManage', '0007_auto_20250805_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridrecord',
            name='Back_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='放回日期'),
        ),
        migrations.AlterField(
            model_name='gridrecord',
            name='Brow_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='留樣日期'),
        ),
        migrations.AlterField(
            model_name='gridrecord',
            name='Take_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拿取日期'),
        ),
    ]
