# Generated by Django 2.1.7 on 2025-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDeviceLNV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50, verbose_name='Category')),
                ('Class', models.CharField(blank=True, max_length=256, null=True, verbose_name='Class')),
                ('Type', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Type')),
                ('Covered_range_for_case', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Covered range for case')),
                ('Require_State', models.CharField(blank=True, max_length=256, null=True, verbose_name='Require State')),
                ('Comments', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Comments')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remark')),
                ('ODM_status', models.CharField(blank=True, max_length=64, null=True, verbose_name='ODM status')),
                ('Purchase_Plan', models.CharField(blank=True, max_length=128, null=True, verbose_name='Purchase Plan')),
                ('Device_Price', models.FloatField(blank=True, max_length=64, null=True, verbose_name='Device Price')),
                ('Device1', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #1')),
                ('Device2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #2')),
                ('Device3', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #3')),
                ('Device4', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #4')),
                ('Device5', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #5')),
                ('Device6', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #6')),
                ('Device7', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #7')),
                ('Device8', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #8')),
                ('Device9', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #9')),
                ('Device10', models.CharField(blank=True, max_length=64, null=True, verbose_name='Device #10')),
            ],
            options={
                'verbose_name': 'TestDeviceLNV',
                'verbose_name_plural': 'TestDeviceLNV',
            },
        ),
    ]
