# Generated by Django 2.1.7 on 2025-04-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDeviceLNV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdevicelnv',
            name='Act_Status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Act_Status'),
        ),
    ]
