# Generated by Django 2.1.7 on 2025-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDeviceLNV', '0002_testdevicelnv_act_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdevicelnv',
            name='Device_Know_Issue',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Device Know Issue'),
        ),
    ]
