# Generated by Django 2.1.7 on 2026-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRetainedSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrowed', models.CharField(max_length=30, verbose_name='借用人')),
                ('Status', models.CharField(max_length=30, verbose_name='借還狀態')),
                ('BorrowQuantity', models.IntegerField(verbose_name='借用數量')),
                ('BorrowedReson', models.CharField(blank=True, max_length=1000, verbose_name='借用用途')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='RetainedSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=40, verbose_name='專案名稱')),
                ('Owner', models.CharField(max_length=30, verbose_name='專案負責人')),
                ('SampleName', models.CharField(max_length=200, verbose_name='樣品名稱')),
                ('Manufacturer', models.CharField(max_length=200, verbose_name='樣品廠商')),
                ('SampleBatch', models.CharField(max_length=500, verbose_name='樣品批次/版本號')),
                ('SampleQuantity', models.IntegerField(verbose_name='樣品數量')),
                ('Retainer', models.CharField(max_length=30, verbose_name='留樣人')),
                ('RetainStart', models.DateField(verbose_name='留樣日期')),
                ('RetainPeriod', models.FloatField(verbose_name='留樣周期(年)')),
                ('RetainPosition', models.CharField(choices=[('Plant5-#23', 'Plant5-#23')], max_length=300, verbose_name='留樣位置')),
                ('BorrowedQuantity', models.IntegerField(verbose_name='已借出數量')),
                ('RemainedQuantity', models.IntegerField(verbose_name='剩餘留樣數量')),
                ('UnderApprovalQuantity', models.IntegerField(verbose_name='簽核中數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='RetainedSampleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrowed', models.CharField(max_length=30, verbose_name='借用人')),
                ('BorrowQuantity', models.IntegerField(verbose_name='借用數量')),
                ('BorrowedReson', models.CharField(blank=True, max_length=1000, verbose_name='借用用途')),
                ('BorrowedStatus', models.CharField(max_length=30, verbose_name='借用狀態')),
                ('ReturnedStatus', models.CharField(max_length=30, verbose_name='借用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Sample', models.ManyToManyField(to='RetainedSample.RetainedSample')),
            ],
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='Sample',
            field=models.ManyToManyField(to='RetainedSample.RetainedSample'),
        ),
    ]
