# Generated by Django 2.1.7 on 2026-02-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetainedSample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainedsample',
            name='ReturnReason',
            field=models.CharField(blank=True, max_length=500, verbose_name='归还原因'),
        ),
        migrations.AddField(
            model_name='retainedsample',
            name='ReturnRequestedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还申请时间'),
        ),
        migrations.AddField(
            model_name='retainedsample',
            name='ReturnRequestedQuantity',
            field=models.IntegerField(default=0, verbose_name='申请归还数量'),
        ),
        migrations.AddField(
            model_name='retainedsample',
            name='ReturnedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间'),
        ),
        migrations.AddField(
            model_name='retainedsample',
            name='ReturnedQuantity',
            field=models.IntegerField(default=0, verbose_name='已归还数量'),
        ),
    ]
