# Generated by Django 2.1.7 on 2026-02-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetainedSample', '0002_auto_20260209_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalretainedsample',
            old_name='Borrowed',
            new_name='Borrower',
        ),
    ]
