# Generated by Django 2.1.7 on 2026-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetainedSample', '0003_auto_20260209_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainedsamplerecord',
            name='RecordType',
            field=models.CharField(blank=True, max_length=30, verbose_name='記錄類型'),
        ),
    ]
