# Generated by Django 2.1.7 on 2026-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetainedSample', '0004_retainedsamplerecord_recordtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalretainedsample',
            name='ApprovedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批准时间'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='ApprovedBy',
            field=models.CharField(blank=True, max_length=100, verbose_name='批准人'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='RejectedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='RejectedBy',
            field=models.CharField(blank=True, max_length=100, verbose_name='拒绝人'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='RemainedQuantity',
            field=models.IntegerField(default=0, verbose_name='剩余借用数量'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='ReturnReason',
            field=models.CharField(blank=True, max_length=500, verbose_name='归还原因'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='ReturnRequestedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还申请时间'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='ReturnRequestedQuantity',
            field=models.IntegerField(default=0, verbose_name='申请归还数量'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='ReturnedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间'),
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='ReturnedQuantity',
            field=models.IntegerField(default=0, verbose_name='已归还数量'),
        ),
    ]
