# Generated by Django 2.1.7 on 2026-02-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetainedSample', '0005_auto_20260209_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalretainedsample',
            name='Sample',
        ),
        migrations.AddField(
            model_name='personalretainedsample',
            name='Sample',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RetainedSample.RetainedSample', verbose_name='留样样品'),
        ),
        migrations.RemoveField(
            model_name='retainedsamplerecord',
            name='Sample',
        ),
        migrations.AddField(
            model_name='retainedsamplerecord',
            name='Sample',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RetainedSample.RetainedSample', verbose_name='留样样品'),
        ),
    ]
