# Generated by Django 2.1.7 on 2026-03-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetainedSample', '0006_auto_20260209_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='留樣位置')),
                ('rack', models.CharField(blank=True, max_length=100, verbose_name='留樣載具')),
                ('cell', models.CharField(max_length=50, verbose_name='No.')),
                ('description', models.TextField(blank=True, verbose_name='目前擺放物品')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '留样位置',
                'verbose_name_plural': '留样位置',
                'ordering': ['area', 'rack', 'cell'],
            },
        ),
        migrations.AlterField(
            model_name='retainedsample',
            name='RetainPosition',
            field=models.CharField(max_length=300, verbose_name='留樣位置'),
        ),
    ]
