# Generated by Django 2.1.7 on 2026-09-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelnv',
            name='DevStatus',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Fixed', 'Fixed'), ('Long', 'Long'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Replaced', 'Replaced')], max_length=64, null=True, verbose_name='設備狀態'),
        ),
    ]
